### ISSUE TITLE
codereview.cc is slow and losing state

### ISSUE THREAD

**Issue by ajsecord** [material-motion/material-motion-team#120]
http://codereview.cc/D1475 is landed, but codereview.cc doesn't show it. I've also heard (but not verified) that emails might not be going out.

Is there a better place for codereview.cc issues?

**Comment by jverkoey** [comment]
Looking into this.

**Comment by jverkoey** [comment]
Am seeing a spike in CPU utilization on the phabricator instance. Diving in.

**Comment by jverkoey** [comment]
Problem found. Looks like a misconfigured repo.

**Comment by jverkoey** [comment]
The culprit was a github repository that we'd mirrored to codereview.cc but have subsequently deleted. codereview.cc was attempting and failing to clone the non-existent repo every few seconds.

**Comment by jverkoey** [comment]
Daemons are back online.

**Comment by jverkoey** [comment]
CPU utilization spiked to 25% a couple days ago (when we deleted the GitHub repo) and is now dropping back to the 13% long-term average.

**Comment by jverkoey** [comment]
To summarize:
- No state was lost.
- Daemons were eating up CPU due to a clone failure that occurred every few seconds.
- This errant daemon appears to have stopped other repositories from being updated. Diffs were not being auto-closed as a result.

Fixing the problem involved the following commands:

```
cd /opt/phabricator
sudo su phabricator-daemon -c "./bin/phd stop"
sudo su phabricator-daemon -c "./bin/phd debug PhabricatorRepositoryPullLocalDaemon"
```

Inspecting the logs revealed that repo 24 was failing to clone. This repo was referencing the material-motion-catalog-apple repository that no longer exists.

I disabled repo 24.

I re-ran the following command to verify that the pull daemon was working as expected:

```
sudo su phabricator-daemon -c "./bin/phd debug PhabricatorRepositoryPullLocalDaemon"
```

I then re-started the daemons:

```
sudo su phabricator-daemon -c "./bin/phd start"
```

**Comment by jverkoey** [comment]
I've created https://github.com/material-foundation/codereview.cc to house any further issues.
