### ISSUE TITLE
When should tools go in their own repo vs here?

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-team#30]
Opening up a discussion for us to discuss thoughts here.

Should we treat the team repo as a monorepo for all of our tools? Should we break things out in to their own repos?

Should we pull mdm out to its own repo so that our tools live separate from the team docs?

**Comment by appsforartists** [comment]
I made a Sublime snippet today to make it easy to add the header to a JS file by typine `lic<tab>`.  I put it [in its own repo](https://github.com/material-motion/material-motion-sublime) because it didn't seem like a good idea to have CLI code and documentation all stuffed into the same package.

Separating out `mdm` from the Team documentation also seems like a good idea.  One repo can be for the `cli` tools - the other can be effectively our wiki.  I'm not bothered by the Team book including documentation for `mdm` - there's already a similar relationship between any of our implementations and the Starmap.

**Comment by jverkoey** [comment]
All tools go in the tools repo now.
